### PR TITLE
chore(deps): bump go-retryablehttp v0.7.5 => v0.7.7

### PR DESCRIPTION
**Pull request by dnwe**
https://github.com/advisories/GHSA-v6v8-xj6m-xwqh

### CODE REVIEW

**Comment by pyrooka** [comment]
Thanks for the PR @dnwe! Please sign the CLA, because it's necessary for merging.

**Comment by dnwe** [comment]
> Thanks for the PR @dnwe! Please sign the CLA, because it's necessary for merging.

Sorry I had clicked the button earlier, but hadn't spotted the "recheck" button. Done now

**Review by pyrooka — APPROVED** [review]
Looks good! I'll change the commit type to fix to trigger a new release.

**Pull request merged**
